name: Centralized CI/CD with Trivy Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t myapp:latest .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: echo "Testing application..."

  security-scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image for Scan
        run: docker build -t myapp:latest .
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:latest'
          format: 'table'

  deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deployment success!"
